services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./:/usr/src/app/
    ports:
      - '80:3000'
    depends_on:
      - db
    env_file:
      - .env
    command: pnpm run start:dev

volumes:
  postgres-data:
