services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: '${PROJECT_NAME}-postgres'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: '${PROJECT_NAME}-pgadmin'
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      CHECK_EMAIL_DELIVERABILITY: ${CHECK_EMAIL_DELIVERABILITY}
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:

  pgadmin-data:
