services:
  app:
    build:
      target: development
    environment:
      - NODE_ENV=dev
    env_file:
      - .env.dev
    volumes:
      - ./:/usr/src/app/
    command: sh -c "npm ci && npm run start:dev"

  postgres:
    env_file:
      - .env.dev

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: '${PROJECT_NAME}-pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      CHECK_EMAIL_DELIVERABILITY: ${CHECK_EMAIL_DELIVERABILITY}
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
