export * from './allergydocuments.service';
export * from './clinicalscanneddocuments.service';
export * from './glscanneddocuments.service';
export * from './labdocuments.service';
export * from './patient.service';
export * from './patientdnrdocuments.service';
export * from './patientreferraldetaildocuments.service';
export * from './scanneddocuments.service';
export * from './taskdocuments.service';
